sudo: required
dist: trusty
language: node_js
addons:
  postgresql: "9.4"
node_js:
  - "8"
before_install:
  - psql -c 'create database faculty_system_test;' -U postgres
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
cache: yarn
script:
  - DATABASE_HOST=localhost DATABASE_USER=postgres DATABASE_PASSWORD= DATABASE_NAME=faculty_system_test APP_ENV=dev APP_SECRET=d41d8cd98f00b204e9800998ecf8427e APP_ROUNDS=10 yarn test
