sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
env:
    - DATABASE_HOST=localhost
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=
    - DATABASE_NAME=faculty_system_test
    - APP_ENV=dev
    - APP_SECRET=d41d8cd98f00b204e9800998ecf8427e
    - APP_ROUNDS=10
before_install:
  - psql -c 'create database faculty_system_test;' -U postgres
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
cache: yarn
script:
  - yarn test
