version: '3.2'
services:
    postgres:
        image: postgres:latest
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=faculty_system

volumes:
    postgres-data: {}
